UPDATE parroquia set COD_PROVINCIA=TRIM(COD_PROVINCIA);
UPDATE parroquia set COD_CANTON=TRIM(COD_CANTON);
UPDATE parroquia set COD_PARROQUIA=TRIM(COD_PARROQUIA);
UPDATE parroquia set NOM_PARROQUIA=TRIM(NOM_PARROQUIA);
UPDATE parroquia set TIP_PARROQUIA=TRIM(TIP_PARROQUIA);
UPDATE parroquia set COD_USU_ALTA=TRIM(COD_USU_ALTA);
UPDATE parroquia set FEC_ALTA=TRIM(FEC_ALTA);
UPDATE parroquia set TIMESTAMP_SIGLO=TRIM(TIMESTAMP_SIGLO);
UPDATE parroquia set COD_USU_MODIF=TRIM(COD_USU_MODIF);
UPDATE parroquia set FEC_MODIF=TRIM(FEC_MODIF);
UPDATE parroquia set FEC_BAJA=TRIM(FEC_BAJA);


UPDATE ciudad set INST_NO=TRIM(INST_NO);
UPDATE ciudad set CITY_CODE=TRIM(CITY_CODE);
UPDATE ciudad set PROVINCE_CODE=TRIM(PROVINCE_CODE);
UPDATE ciudad set DESCRIPTION=TRIM(DESCRIPTION);
UPDATE ciudad set STATUS=TRIM(STATUS);
UPDATE ciudad set REGION_CODE=TRIM(REGION_CODE);
UPDATE ciudad set UDEV_REGION=TRIM(UDEV_REGION);
UPDATE ciudad set PUBL_AMOUNT=TRIM(PUBL_AMOUNT);
UPDATE ciudad set CHQ_DELIVERY=TRIM(CHQ_DELIVERY);



